#!/usr/bin/env bash

set -eux

rm -rf  /.autorelabel

# Remove development and kernel source packages
yum -y remove bison
yum -y remove flex
yum -y remove gcc
yum -y remove gcc-c++
yum -y remove kernel-devel
yum -y remove kernel-headers
yum -y remove cloog-ppl
yum -y remove cpp
yum -y clean all

rm -rf /etc/udev/rules.d/70-persistent-net.rules
mkdir /etc/udev/rules.d/70-persistent-net.rules
rm -rf /dev/.udev/

for ndev in $(ls -1 /etc/sysconfig/network-scripts/ifcfg-*); do
  if [ "$(basename "${ndev}")" != "ifcfg-lo" ]; then
    sed -i '/^HWADDR/d' "$ndev";
    sed -i '/^UUID/d' "$ndev";
  fi
done

echo "* Remove temporary files"
rm -rf /tmp/*
rm -rf /var/tmp/*
rm -rf /root
mkdir /root
chown -R root:root /root
chmod -R 700 /root
yum reinstall rootfiles -y

echo "* Remove ssh server keys"
rm -rf /etc/ssh/*_host_*

echo "* Remove the PAM data"
rm -rf /var/run/console/*
rm -rf /var/run/faillock/*
rm -rf /var/run/sepermit/*

echo "* Remove the process accounting log files"
if [ -d /var/log/account ]; then
  rm -f /var/log/account/pacct*
  touch /var/log/account/pacct
fi

echo "* Remove the crash data generated by ABRT"
rm -rf /var/spool/abrt/*

echo "* Remove email from the local mail spool directory"
rm -rf /var/spool/mail/*
rm -rf /var/mail/*

echo "* Remove the local machine ID"
if [ -d /etc/machine-id ]; then
  rm -f /etc/machine-id
  touch /etc/machine-id
fi
if [ -d /var/lib/dbus/machine-id ]; then
  rm -f /var/lib/dbus/machine-id
  touch /var/lib/dbus/machine-id
fi

echo "* Clearing last login information"
>/var/log/lastlog
>/var/log/wtmp
>/var/log/btmp

echo "* Empty log files"
find /var/log -type f | while read -r f; do echo -ne '' > "$f"; done;

echo "* Cleaning up leftover dhcp leases"
rm -f /var/lib/dhclient/*

echo "* Remove resolv.conf"
> /etc/resolv.conf

echo "* Remove Bash history"
unset HISTFILE
rm -f /root/.bash_history

echo "* Remove YUM UUID"
rm -f /var/lib/yum/uuid

echo "* Remove YUM cache"
find /var/cache/yum/ -type f -exec rm -f {} \;

echo "* Removing caches"
find /var/cache -type f -exec rm -rf {} \;

echo "* Recreating RPM DB"
rm -f /var/lib/rpm/__db*
rpm --rebuilddb
